const business = {
  name: 'ONE: Personal Training',
  tagline: 'TRAIN SMARTER, MOVE BETTER, GET STRONGER',
  description: 'Inspiring clients to move better and get stronger. Established in Mayfair in 2022, ONE: Personal Training brings a highly developed and effective method, centred around the art of movement coupled with strength training, to create stronger, leaner, and more efficient bodies.',
  city: 'Mayfair, London',
  area: 'Mayfair',
  address: '35 South Audley Street, Mayfair, London, United Kingdom W1K 2PJ',
  shortAddress: '35 South Audley Street, London, W1K 2PJ',
  phone: '+44 (0) 7740461947',
  phoneRaw: '+447740461947',
  whatsapp: '+44 (0) 7740461947',
  whatsappRaw: '447740461947',
  email: 'info@onepersonaltraining.co.uk',
  instagram: 'https://www.instagram.com/one_personal_training/',
  googleMaps: 'https://maps.app.goo.gl/vT3cg6vu23ZU6bqr5',
  openingHours: [
    { day: 'Monday', hours: '06:00 – 21:00' },
    { day: 'Tuesday', hours: '06:00 – 21:00' },
    { day: 'Wednesday', hours: '06:00 – 21:00' },
    { day: 'Thursday', hours: '06:00 – 21:00' },
    { day: 'Friday', hours: '06:00 – 21:00' },
    { day: 'Saturday', hours: '07:00 – 17:00' },
    { day: 'Sunday', hours: '08:00 – 17:00' },
  ],
  navLinks: [
    { label: 'Home', path: '/' },
    { label: 'Services', path: '/services' },
    { label: 'Studio', path: '/studio' },
    { label: 'About', path: '/about' },
    { label: 'Schedule Your Session', path: '/book' },
    { label: 'Contact', path: '/contact' },
  ],
  hero: {
    eyebrow: 'Mayfair · Personal Training',
    headline: 'Train Smarter, Move Better, Get Stronger',
    supporting: 'Strength, movement, and recovery — tailored to you, in the heart of Mayfair.',
    trustLine: 'Open Monday – Saturday · 35 South Audley Street, London',
    primaryCta: 'Schedule Your Session',
    secondaryCta: 'Contact Us',
    image: 'https://onepersonaltraining.co.uk/wp-content/uploads/2023/06/ONE_HEADER2.jpg',
  },
  services: [
    {
      title: 'One:One Personal Training',
      description: 'Strength, movement, balance, posture, agility and co-ordination — a holistic full body approach to training.',
      fullDescription: 'Our approach to Personal Training builds strength and improves movement progressively, developing a range of exercises to best suit individual needs. Our 60-minute training sessions are progressive, efficient and energising. Sessions include a mixture of strength, movement, balance, posture, agility and co-ordination for a holistic, full body approach to training. Through our varied programmes, we create higher levels of mental stimulation, resulting in high client retention.\n\nWe believe in integrating sport-specific training and exercises where relevant, to progress clients in current sports and reconnect with previously enjoyed activities. Our coaching can be adapted to all sports, including tennis, football, padel and running.',
      image: 'https://onepersonaltraining.co.uk/wp-content/uploads/2024/05/One_1237-scaled-e1716937775624.jpg',
    },
    {
      title: 'Rehabilitation from Injury',
      description: 'Alleviating pain through movement, restoring neurological pathways after injury, surgery or illness.',
      fullDescription: 'Sessions are focused on alleviating pain though movement, helping to restore neurological pathways to allow correct muscle and joint function following injury, surgery or illness.\n\nOur trainers rehabilitate complex medical cases and regularly receive referrals from neurosurgeons, orthopaedic surgeons, chiropractors, physiotherapists and osteopaths. We work alongside therapists to provide the most comprehensive, effective and restorative service possible.\n\nGait and postural analysis for walking and running. Ligament and muscular strains and tears. Shoulder impingements. Lower back pain. Herniated discs. Stiff neck. Hip bursitis. Hip and knee replacements. General lack of flexibility. Poor balance and co-ordination.',
      image: 'https://onepersonaltraining.co.uk/wp-content/uploads/2023/05/One_115-scaled-e1717103114726.jpg',
    },
    {
      title: 'One:One Sculpt',
      description: 'A fusion of pilates and strength using body weight, dumbbells and bands — low impact, high definition.',
      fullDescription: 'A fusion of pilates and strength using body weight, dumbbells and bands. A low impact session with resistance to tone, lift and shape, creating a strong, lean physique.',
      image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1600&q=80',
    },
    {
      title: 'Virtual Online Training',
      description: 'Train from home or anywhere in the world with an experienced ONE: Trainer, adaptable to any environment.',
      fullDescription: 'Train from the comfort of your own home or from anywhere in the world with an experienced ONE: Trainer. Adaptable to any training environment, we will guide you through your personalised programme, suited to your needs, at a time that suits you. Training can be with or without equipment.',
      image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1600&q=80',
    },
    {
      title: 'One:One Boxing Coaching',
      description: 'Learn to box with correct technique — technical, engaging, building speed, power and resilience.',
      fullDescription: 'Learn to box, teaching you the correct skills right from the start. Sessions are technical, engaging and a great workout, helping to improve movement, speed, power, stamina, fitness and resilience.',
      image: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1600&q=80',
    },
    {
      title: 'One:One Mat Pilates',
      description: 'Full-body strength and mobility through deep, low impact movement — building long-lasting muscle tone.',
      fullDescription: 'Our focused Pilates sessions are designed to build full-body strength and mobility, through deep, low impact movement. Mat Pilates creates long-lasting muscle tone, particularly focusing on the core and emphasising the mind-body connection. Our Pilates sessions will leave you feeling elongated and energised.',
      image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1600&q=80',
    },
    {
      title: 'One:One Yoga',
      description: 'A mindful blend of movement and alignment — building strength, balance, and flexibility.',
      fullDescription: 'A mindful blend of movement and alignment designed to build strength, balance, and flexibility. This low-impact flow connects breath with posture to ground the body, calm the mind, and support a sense of ease and well-being.',
      image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=1600&q=80',
    },
    {
      title: 'Massage',
      description: 'Bespoke and traditional massages — sports, deep tissue, Swedish, lymphatic, abdominal and stretching.',
      fullDescription: 'We offer a range of bespoke and traditional massages to help you relax, recuperate and unwind.\n\nSports massage / Deep tissue massage / Swedish massage / Lymphatic massage / Abdominal massage / Stretching massage',
      image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=1600&q=80',
    },
    {
      title: 'Home, Office or Hotel Training',
      description: 'In-person training, stretching and massage at your home, office or hotel — tailored to your needs.',
      fullDescription: 'For the upmost convenience and efficiency, our trainers and therapists are available to come to your home, office or hotel gym, to deliver your bespoke workout, stretch or massage, completely tailored to your needs.',
      image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1600&q=80',
    },
    {
      title: 'Functional Nutrition & Sleep Recovery',
      description: 'Nutritional and sleep recovery protocols through our trusted partners, Omni Athlete.',
      fullDescription: 'Nutritional and sleep recovery protocols, often incorporating blood analysis, through our trusted partners, Omni Athlete.\n\nWe help you reclaim movement as a daily practice to optimise your physiology, linked with personalised nutrition strategies and recovery protocols to address the full stress-recovery cycle — balancing your nervous system, improving emotional regulation, and enhancing physical restoration.',
      image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1600&q=80',
    },
  ],
  about: {
    intro: 'Established in Mayfair in 2022, ONE: Personal Training brings a highly developed and effective method, centred around the art of movement coupled with strength training, to create stronger, leaner, and more efficient bodies.',
    body: 'The team at ONE: are experts in functional training, helping clients improve their strength, mobility, posture, balance, agility and co-ordination.\n\nAfter 15 years in the fitness industry working with high profile clients, founder Henry Barratt has a tried and tested approach to helping people achieve their goals, by constantly varying exercises, ranges of movement, loads and reps all in a subtle, yet meticulously planned way.\n\nThis philosophy is now shared with a small and agile team of trainers, focusing on building long-term, transparent and supportive relationships with clients. Our training is heavily personalised, designed on unique needs and shared with constant support.',
    image: 'https://onepersonaltraining.co.uk/wp-content/uploads/2023/05/One_1463-scaled.jpg',
  },
  whyChooseUs: [
    {
      number: '01',
      title: 'Expert-Led Training',
      description: 'Work with certified professionals who understand the body, movement, and recovery at the deepest level.',
    },
    {
      number: '02',
      title: 'Personalised to You',
      description: 'Every programme is built around your body, your goals, and your lifestyle — nothing generic.',
    },
    {
      number: '03',
      title: 'Mayfair Studio',
      description: 'A luxury, private training space in the heart of London with state-of-the-art equipment.',
    },
    {
      number: '04',
      title: 'Holistic Approach',
      description: 'Strength, nutrition, sleep, recovery — we address every part of the stress-recovery cycle.',
    },
  ],
  founder: {
    name: 'Henry Barratt',
    title: 'Founder',
    image: 'https://onepersonaltraining.co.uk/wp-content/uploads/2023/05/One_1463-scaled.jpg',
    bio: 'Founder Henry Barratt began his career in professional rugby, playing for Harlequins, Cornish Pirates, London Wasps and England U19 and U21\'s, featuring in two U21 World Cups. A place that taught him a passion for health and wellness. Experiencing a multitude of injuries grew his perspective on the body, giving him in depth understanding of how to overcome both physical and physiological obstacles with empathy, compassion and determination.\n\nThis outlook grew into a philosophy of training, leading to an exciting career as a personal trainer to celebrities and high profile clients, often entailing international travel. In 2022, as the importance of a personal training is more prevalent than ever, Henry founded ONE: PERSONAL TRAINING',
    qualifications: [
      'BSc – Business Management',
      'NASM Certified Personal Trainer – 1st Class honours',
      'Advanced Functional Trainer',
      'Injury Rehabilitation Specialist',
      'Fitness Diploma In Functional Performance',
      'Stuart McGill – Back Rehabilitation',
      'Stuart McGill – Performance Back Strength',
      'Advanced Performance Boxing Coach',
      'Boxing Instructor',
      'Golf Performance Specialist',
      'Speed Development',
      'Vivobarefoot Running Coach',
      'Watt Bike Coach',
      'Pre and Post Natal Diploma',
      'Breath Practitioner',
    ],
    quote: 'The journey of the client is important, that they are present, and willing to learn about their bodies in order to unlock their own unique potential – the balance of eating, sleeping and training. This progression will not be completely linear, it will rise and fall, ebb and flow, but as long as the trajectory is moving upwards, then we are on the right path.',
  },
  foundingPrinciples: [
    {
      title: 'Education',
      description: 'Chatting with clients during sessions about training, sleep, nutrition, recovery, injury prevention, myths and FAQ\'s enables a deeper understanding of their own bodies and its capabilities. We encourage exercise five times a week in various formats to encourage a higher metabolic rate, physical and mental stimulation and the power of endorphins.',
    },
    {
      title: 'Connection',
      description: 'Key to the success of ONE: for both trainers and clients is their connection with the brand and the people behind it. The trainers connect with the ONE: philosophy and feel happy, valued and are rewarded well, whilst clients feel supported, understood and valued by their trainer.',
    },
    {
      title: 'Enjoyment',
      description: 'Workout programmes are built not only for physical fitness, but also for mental stimulation. Using plans that require thought and brain activation allows clients to improve their overall health, developing their fitness with fun and enjoyment. Visiting a ONE: studio is always a positive and uplifting experience.',
    },
  ],
  team: [
    {
      name: 'Tim',
      role: 'Personal Trainer and Nutrition Coach',
      image: 'https://onepersonaltraining.co.uk/wp-content/uploads/2024/06/untitled-109390-scaled-e1717405618846.jpg',
      expertise: ['Body compositional change', 'Strength', 'Hypertrophy', 'Injury rehabilitation', 'Posture'],
      bio: 'Tim is a Henselmans Certified Personal Trainer and holds UK Level 3 Certifications in both Personal Training & Nutrition. Tim joined the ONE: PT team in April 2023, where he runs the online nutrition & programming services, as well as taking over 20 in-person training sessions per week. He has an international client base, working with clients in Germany, the US, Russia and South Korea. He also has experience of international travel with clients, providing bespoke training programs and working with private chefs to create meal plans during travel. Tim has worked with a number of high-profile clients, including ex-international sportsmen and celebrity chefs.\n\nTim\'s career is marked by versatility and adaptability, having worked in multiple training settings, including one-to-one personal training, golf and leisure fitness, and large group PT sessions. Prior to his current role, Tim accumulated six years of experience in Sports Licensing & Fitness Product Development. During this period, he collaborated with some of the world\'s most renowned brands, including UEFA, FIFA, major football clubs, the Rugby World Cup, and the Olympics. He made the transition from the fitness product development to the coaching industry in 2019, driven by a desire to help others achieve their fitness goals and lead healthier lives.\n\nOutside of the gym, Tim is passionate about promoting an active lifestyle through various outdoor activities. He runs free walking and hiking trips within the UK and organizes hiking retreats to stunning locations across Europe. He\'s travelled to over 40 countries, and has lived in South Korea, Colombia and Mexico. His love for bodybuilding is another testament to his dedication to fitness and personal growth.',
    },
    {
      name: 'Cristina',
      role: 'Personal Trainer and Holistic Coach',
      image: 'https://onepersonaltraining.co.uk/wp-content/uploads/2024/06/PHOTO-2024-06-15-11-10-54-e1718484094904.jpg',
      expertise: ['Body transformations', 'Strength', 'Hypertrophy', 'Injury rehabilitation', 'Corrective posture', 'Yoga & flexibility training', 'Thai stretch therapy'],
      bio: 'With a vibrant Mexican heritage and over 13 years of experience in the fitness industry, Cristina is a seasoned professional dedicated to transforming lives through fitness and holistic wellness. Cristina\'s journey began in the world of fitness in 2011, where a passion for health and wellbeing quickly grew into a successful career.\n\nIn 2015, Cristina turned to bodybuilding and achieved remarkable success, winning a pro card in London and clinching the World Championship title in Las Vegas that same year. This triumph propelled Cristina onto the global stage, where extensive competition experience broadened their expertise and deepened their understanding of fitness and bodybuilding.\n\nAs Cristina traveled and competed worldwide, a wealth of knowledge was amassed, forming the foundation of the effective and personalized training methods used today. However, through these experiences, Cristina realized that true health encompasses more than just physical appearance. This insight led to a transformative shift towards holistic coaching.\n\nNow, as a holistic coach, Cristina aims to help clients achieve not only their fitness goals but also enhance their overall well-being. By integrating principles of physical fitness, Thai stretch therapy, mental health, and nutritional balance, Cristina provides comprehensive coaching that ensures clients not only look their best but also feel their best.',
    },
    {
      name: 'James',
      role: 'Personal Trainer',
      image: 'http://onepersonaltraining.co.uk/wp-content/uploads/2024/06/PHOTO-2024-06-03-13-51-04-e1717676443701.jpg',
      expertise: ['Hypertrophy', 'Strength', 'Sports Specific training', 'Calisthenics'],
      bio: 'James is a Level 3 NASM Certified Personal Trainer in both the UK and the USA, with extensive experience helping to run a clinical healthcare and personal training business in central London alongside a cardiac specialist. He specialises in transformative online programs, personalised one-on-one coaching, and comprehensive nutritional guidance. Since joining the ONE PT team in 2023, James has focused on calisthenics and strength training, working with a diverse and dedicated clientele.\n\nOver the past seven years, James has worked with individuals from various backgrounds both in the UK and internationally. His experience spans from holistic rehabilitative training in Cape Town to mindset coaching business owners and young professionals in the USA. Now based in London, he collaborates with athletes, corporate professionals, and high-profile clients. James places a unique emphasis on understanding each client\'s specific needs and belief systems to foster sustainable, high-level performance.\n\nDriven by a deep passion for helping people become their healthiest selves, James integrates meticulous attention to both external fitness and internal well-being, offering holistic support that enables growth and results.',
    },
    {
      name: 'Issy',
      role: 'Mat Pilates – One:One & Group Classes',
      image: 'https://onepersonaltraining.co.uk/wp-content/uploads/2024/06/PHOTO-2024-06-03-14-01-28-e1717676586158.jpg',
      expertise: ['Mat Pilates', 'Reformer Pilates', 'Athletic coaching', 'Movement'],
      bio: 'With years of experience as a competitive athlete and professional model, Issy knows the importance of a healthy lifestyle. It was through athletics she was introduced to Pilates and the benefits it has for the mind and body.\n\nHealth and fitness was always something Issy had a passion for, leading her to study Sports and Exercise Science before going on to study with British Athletics Sports Excellence at Loughborough College.\n\nIt was whilst training as an athlete that Issy\'s other passion emerged, as she was introduced to Pilates. She ranked highly for her country in high jump, leading her to represent for England, this enabled her to work alongside Olympic champion coaches and athletes.\n\nWorking with people to help them move well and understand their bodies is something Issy has particularly enjoyed from a young age. She started her coaching career from the age of 15 at her local athletics club. Spending many years as an athletics coach, Issy then moved into teaching Reformer and Mat Pilates.\n\nIssy works with private clients and teaches group classes, where she helps clients understand both the short-term performance and long-term health benefits that Pilates brings.',
    },
    {
      name: 'Dr Martin Saweirs',
      role: 'ONE: Personal Training Doctor',
      image: 'https://onepersonaltraining.co.uk/wp-content/uploads/2024/07/Dr-Martin-Saweirs-e1720957299412.jpg',
      expertise: ['General Practice', 'Clinical Dermatology', 'Private GP'],
      bio: 'MRCGP, MBChB, BSc (Hons), PGDip Clinical Dermatology\n\nDr Martin Saweirs is the founder of Dr Martin GP – Private General Practitioners and is the ONE:Personal Training Doctor, looking after our clients and trainers with the utmost care.\n\nDr Martin and his experienced team of Private GPs offer flexible appointments from 9am to 6pm weekdays, in person and also available via video/telephone, covering a full range of general medical problems for the whole family.',
    },
  ],
  studio: {
    title: 'Luxury, home from home studio',
    description: 'ONE: Mayfair is designed for luxury, providing the best personal training experience in London, perhaps the World. A home from home approach, that leaves clients feeling calm and relaxed.\n\nThe studio has three individual training areas, so a maximum of three clients working out at the same time, each with their own state of the art equipment.\n\nThe studio has two luxury private shower and changing rooms, soft lighting, oak parquet flooring, green plants, fluffy towels and Aesop products.',
    facilities: [
      'Handmade squat racks with integrated cable systems, made in Belfast',
      'Customised dumbbells up to 50kg',
      'Power sled, made in Belfast',
      'Handmade rack attachments, made in Somerset',
      'Technogym Skill Run Treadmill with sled and parachute functions',
      'Watt Bike Atom used by the British Olympic cycling team',
    ],
    images: [
      'https://onepersonaltraining.co.uk/wp-content/uploads/2023/05/One_546-scaled.jpg',
      'https://onepersonaltraining.co.uk/wp-content/uploads/2023/06/One_2034-scaled.jpg',
    ],
    cta: 'Schedule Your Session',
  },
  pressArticles: [
    {
      publication: 'Luxury Lifestyle Magazine',
      title: 'Meet Mayfair\'s New PT Star: The Discreet Henry Barratt',
      url: 'https://www.luxurylifestylemag.co.uk/health-wellbeing/meet-mayfairs-new-pt-star-the-discreet-henry-barratt/',
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80',
    },
    {
      publication: 'Luxuriate Life',
      title: 'Henry Barratt: Holistic Fitness Expert',
      url: 'https://luxuriate.life/henry-barratt-holistic-fitness-expert/',
      image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=600&q=80',
    },
    {
      publication: 'Time and Leisure',
      title: 'Strength Training: Why Strength is Our Superpower as We Get Older',
      url: 'https://www.timeandleisure.co.uk/health-wellbeing/strength-training-why-strength-is-our-superpower-as-we-get-older/',
      image: 'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=600&q=80',
    },
  ],
  contact: {
    heading: 'Contact a member of the ONE: team for a consultation',
    description: 'Our trainers are always on hand to answer any questions about our services.\nTo book a consultation, please contact us using the details below.',
    phoneAlt: '+0333 253 7001',
  },
  testimonials: [
    {
      name: 'Graham Davies',
      source: 'Google Reviews',
      rating: 5,
      text: 'An Exceptional Personal Training Experience — Truly World-Class. If you\'re looking for an elite, niche, and truly bespoke training experience that goes far beyond the norm, this is the place. Whether you\'re local or flying in from abroad, ONE Personal Training is worth every second. Can\'t recommend them enough.',
    },
    {
      name: 'Kate Beckinsale',
      source: 'Actress',
      rating: 5,
      text: 'One of the best trainers I have ever worked with. Never boring and constantly new ideas to accommodate your personal fitness goals, any injuries or intense dislikes. Could not recommend more.',
    },
    {
      name: 'Daniel Humm',
      source: 'Michelin Star Chef – Eleven Madison Park, NY',
      rating: 5,
      text: 'Super approachable but also totally professional and knowledgeable. A workout that is balanced, so that your whole body benefits. Tailored programs to your skills, interests, and goals making sure you are successful.',
    },
    {
      name: 'Tara Kirwan',
      source: 'Google Reviews',
      rating: 5,
      text: 'I was referred to One Personal Training following a recurring back issue and I\'m so glad I was. After only a few sessions, movement in my back dramatically improved. I could feel my overall body strength increasing, better supporting and protecting my back and body overall.',
    },
    {
      name: 'Audrey L Libert',
      source: 'Google Reviews',
      rating: 5,
      text: 'I couldn\'t recommend ONE: Personal Training enough! Having tried many PT sessions over the last 10 years in London, this is by far the best I\'ve ever experienced. Their approach is very different from most PTs. They understand all bodies and adapt to your needs during the session.',
    },
    {
      name: 'Charlie Catterall',
      source: 'Google Reviews',
      rating: 5,
      text: 'Hugely impressed by Henry and the team at ONE. They\'ve created a unique vibe and experience that was a refreshing new approach to training. The one on one training offered a bespoke service, but the joint use of the area creates a nice community feel to all users.',
    },
  ],
  stats: [
    { label: 'Years of Excellence', value: 4, suffix: '+' },
    { label: 'Sessions Completed', value: 10000, suffix: '+' },
    { label: 'Client Transformations', value: 500, suffix: '+' },
    { label: 'Star Rating', value: 5, suffix: '.0' },
  ],
  faq: [
    {
      question: 'What should I expect from my first session?',
      answer: 'Your first session includes a full consultation and movement assessment. We\'ll discuss your goals, any injuries or limitations, and build a programme tailored specifically to you. No two sessions are the same.',
    },
    {
      question: 'Do I need to be fit to start?',
      answer: 'Not at all. Our trainers work with all levels, from complete beginners to professional athletes. Every programme is built around your current ability and progresses at your pace.',
    },
    {
      question: 'What should I bring to a session?',
      answer: 'Just yourself in comfortable workout clothing. We provide towels, filtered water, and Aesop products in our changing rooms. All equipment is provided.',
    },
    {
      question: 'How is ONE: different from a regular gym?',
      answer: 'We are a private, appointment-only studio with a maximum of three clients at any time. Each session is one-to-one with an expert trainer who designs and coaches your programme. There are no crowded floors, no waiting for equipment, and no generic plans.',
    },
  ],
};

export default business;
